services:
  project-manager-frontend:
    restart: always
    image: project-manager-frontend-lastest
    container_name: project-manager-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:80"
    volumes:
      - sca_node_modules:/app/node_modules
volumes:
  sca_node_modules:
